// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// LongQuest_Gibbs_CEBQ_biv
List LongQuest_Gibbs_CEBQ_biv(List data_list, List MCMC_list, List Param_list);
RcppExport SEXP _LongQuest_LongQuest_Gibbs_CEBQ_biv(SEXP data_listSEXP, SEXP MCMC_listSEXP, SEXP Param_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type data_list(data_listSEXP);
    Rcpp::traits::input_parameter< List >::type MCMC_list(MCMC_listSEXP);
    Rcpp::traits::input_parameter< List >::type Param_list(Param_listSEXP);
    rcpp_result_gen = Rcpp::wrap(LongQuest_Gibbs_CEBQ_biv(data_list, MCMC_list, Param_list));
    return rcpp_result_gen;
END_RCPP
}
// LongQuest_Gibbs_CEBQ_biv_1coef
List LongQuest_Gibbs_CEBQ_biv_1coef(List data_list, List MCMC_list, List Param_list);
RcppExport SEXP _LongQuest_LongQuest_Gibbs_CEBQ_biv_1coef(SEXP data_listSEXP, SEXP MCMC_listSEXP, SEXP Param_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type data_list(data_listSEXP);
    Rcpp::traits::input_parameter< List >::type MCMC_list(MCMC_listSEXP);
    Rcpp::traits::input_parameter< List >::type Param_list(Param_listSEXP);
    rcpp_result_gen = Rcpp::wrap(LongQuest_Gibbs_CEBQ_biv_1coef(data_list, MCMC_list, Param_list));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_LongQuest_LongQuest_Gibbs_CEBQ_biv", (DL_FUNC) &_LongQuest_LongQuest_Gibbs_CEBQ_biv, 3},
    {"_LongQuest_LongQuest_Gibbs_CEBQ_biv_1coef", (DL_FUNC) &_LongQuest_LongQuest_Gibbs_CEBQ_biv_1coef, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_LongQuest(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
