# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LongQuest_Gibbs_CEBQ_biv <- function(data_list, MCMC_list, Param_list) {
    .Call(`_LongQuest_LongQuest_Gibbs_CEBQ_biv`, data_list, MCMC_list, Param_list)
}

LongQuest_Gibbs_CEBQ_biv_1coef <- function(data_list, MCMC_list, Param_list) {
    .Call(`_LongQuest_LongQuest_Gibbs_CEBQ_biv_1coef`, data_list, MCMC_list, Param_list)
}

